### PR TITLE
Update language list and minor improvements

### PR DESCRIPTION
**Pull request by eduardom**
Hi, I am back, it is Eduardo Mucelli R. O. here. I am looking back to my old applets and seeing if they are ok and up to date. I will try to work on this things in the next weeks, and then I will get back to new applets. Cheers.

### CODE REVIEW

**Comment by matttbe** [comment]
Hi Eduardo,

Welcome back!

Looks nice, as usual, merged! :-)

PS: feel free to also update `list.conf`file ;-)

**Comment by eduardom** [comment]
Hey matttbe,

Thanks. Since I've been out for a long time, I've forgot: what is the list.conf about?

Thanks.

**Comment by matttbe** [comment]
It's the file read by the dock in order to now if it has to update it or not. You can update it if there is a new version of your applet. See commit 386c97c ;-)

**Comment by eduardom** [comment]
I see, thanks. I thought that CD would build this up based on the last-modif. Thanks for the info.

**Comment by matttbe** [comment]
PS: Welcome in the Third Party team!

You can now directly push to this repo. But you can still create pull requests if you prefer ;-)

PS²: It's a detail but because there are multiple applets in this repo, it's would be nicer if you can add the name of your applet as prefix for your commit's message.

**Pull request merged**
